spring.config.name=application

server.servlet.encoding.enabled=true
server.servlet.encoding.charset=UTF-8
server.port=8080
server.address=127.0.0.1

spring.task.scheduling.pool.size=3

spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:file:./price-tracker
spring.datasource.username=sa
spring.datasource.password=123
spring.h2.console.path=/h2-console
spring.h2.console.settings.trace=false
spring.h2.console.settings.web-allow-others=false
spring.h2.console.enabled=true

spring.cache.type=none

app.mail.enabled=false
app.mail.debug=false
app.mail.admin=
app.mail.from=
app.mail.host=
app.mail.username=
app.mail.password=
app.mail.properties.transport.protocol=smtp
#app.mail.properties.mail.smtp.port=465
app.mail.properties.smtp.port=587
app.mail.properties.smtp.connectiontimeout=3000
app.mail.properties.smtp.timeout=3000
app.mail.properties.smtp.writetimeout=3000
app.mail.properties.smtp.auth=true
app.mail.properties.smtp.starttls.enable=true
app.mail.properties.smtp.starttls.required=true

app.parser.cron.enabled=true
# cron delay. 3600000 - one hour
app.parser.cron.initial-timeout=3600000
app.parser.cron.interval=3600000

spring.profiles.include=custom
